### ISSUE TITLE
[Issue] Stylesheets are not loading

### ISSUE THREAD

**Issue by v3DJG6GL** [knrdl/hubleys-dashboard#157]
I'd love to use this dashboard, since it is one of the only with forward auth possibilites.
But within my deployment, Hubleys seems to have problems with loading stylesheets:
![image](https://github.com/knrdl/hubleys-dashboard/assets/72495210/f7e2c939-9606-4385-a81f-0750a568e583)
Here the console output from Firefox:
![image](https://github.com/knrdl/hubleys-dashboard/assets/72495210/4aba1c89-7927-4c46-8ab9-4af17ec318f9)

My environment:
OS: TrueNAS SCALE 22.12.2
I used the [custom-app from TrueCharts](https://truecharts.org/charts/stable/custom-app/) to deploy the hubleys-dashboard. And otherwise I had no issues with other docker images I deployed this way...

**Comment by knrdl** [comment]
Hi, I don't have a computer here right now, so can't test it. But please try to open one of the requested files in your Webbrowser and send the screenshot. My guess is that ingress is not configured correctly so you get 404 html responses.

**Comment by v3DJG6GL** [comment]
Hi, thanks for you reply!
Yes, I get a 404.

Here are the logs which are generated when opening the url:

> 2023-09-11 13:33:00.540672+00:00Logo file "authelia.png" could not be found, ignoring image.
> 2023-09-11 13:33:00.541197+00:00Logo file "grafana.svg" could not be found, ignoring image.
> 2023-09-11 13:33:00.774079+00:00Error: Not found: /_app/immutable/assets/index.32503cb2.css
> 2023-09-11 13:33:00.774168+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.774224+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.774244+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.774261+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.774277+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.781038+00:00Error: Not found: /_app/immutable/assets/0.85665951.css
> 2023-09-11 13:33:00.781138+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.781175+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.781205+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.781270+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.781297+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.787282+00:00Error: Not found: /_app/immutable/chunks/singletons.26e36902.js
> 2023-09-11 13:33:00.787360+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.787408+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.787425+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.787441+00:00at runNextTicks (node:internal/process/task_queues:60:5)
> 2023-09-11 13:33:00.787456+00:00at process.processImmediate (node:internal/timers:449:9)
> 2023-09-11 13:33:00.787482+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.787500+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.792680+00:00Error: Not found: /_app/immutable/assets/5.87438bb4.css
> 2023-09-11 13:33:00.792755+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.792802+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.792820+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.792836+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.792863+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.801022+00:00Error: Not found: /_app/immutable/entry/app.586a27af.js
> 2023-09-11 13:33:00.801104+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.801124+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.801142+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.801186+00:00at runNextTicks (node:internal/process/task_queues:60:5)
> 2023-09-11 13:33:00.801203+00:00at process.processImmediate (node:internal/timers:449:9)
> 2023-09-11 13:33:00.801218+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.801246+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.806114+00:00Error: Not found: /_app/immutable/chunks/parse.bee59afc.js
> 2023-09-11 13:33:00.806195+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.806216+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.806258+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.806275+00:00at runNextTicks (node:internal/process/task_queues:60:5)
> 2023-09-11 13:33:00.806291+00:00at process.processImmediate (node:internal/timers:449:9)
> 2023-09-11 13:33:00.806306+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.806332+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.811375+00:00Error: Not found: /_app/immutable/entry/start.6cfe8141.js
> 2023-09-11 13:33:00.811453+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.811473+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.811516+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.811533+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.811549+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.820268+00:00Error: Not found: /_app/immutable/nodes/0.b4c77e69.js
> 2023-09-11 13:33:00.820363+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.820384+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.820400+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.820418+00:00at runNextTicks (node:internal/process/task_queues:60:5)
> 2023-09-11 13:33:00.820448+00:00at process.processImmediate (node:internal/timers:449:9)
> 2023-09-11 13:33:00.820464+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.820480+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.824516+00:00Error: Not found: /_app/immutable/chunks/0.ff6d873d.js
> 2023-09-11 13:33:00.824625+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.824647+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.824663+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.824679+00:00at runNextTicks (node:internal/process/task_queues:60:5)
> 2023-09-11 13:33:00.824707+00:00at process.processImmediate (node:internal/timers:449:9)
> 2023-09-11 13:33:00.824724+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.824740+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.828519+00:00Error: Not found: /_app/immutable/chunks/preload-helper.a4192956.js
> 2023-09-11 13:33:00.828621+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.828642+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.828658+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.828674+00:00at runNextTicks (node:internal/process/task_queues:60:5)
> 2023-09-11 13:33:00.828702+00:00at process.processImmediate (node:internal/timers:449:9)
> 2023-09-11 13:33:00.828719+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.828735+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.832361+00:00Error: Not found: /_app/immutable/chunks/scheduler.bd3fd4b8.js
> 2023-09-11 13:33:00.832460+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.832481+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.832497+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.832513+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.832539+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.838151+00:00Error: Not found: /_app/immutable/chunks/stores.4644daa5.js
> 2023-09-11 13:33:00.838216+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.838235+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.838277+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.838294+00:00at runNextTicks (node:internal/process/task_queues:60:5)
> 2023-09-11 13:33:00.838311+00:00at process.processImmediate (node:internal/timers:449:9)
> 2023-09-11 13:33:00.838327+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.838357+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.841375+00:00Error: Not found: /_app/immutable/chunks/index.b4f43381.js
> 2023-09-11 13:33:00.841437+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.841455+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.841497+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.841514+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.841530+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.845108+00:00Error: Not found: /_app/immutable/chunks/index.da3b84ee.js
> 2023-09-11 13:33:00.845188+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.845209+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.845225+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.845281+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.845299+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.849168+00:00Error: Not found: /_app/immutable/chunks/each.4876bb1f.js
> 2023-09-11 13:33:00.849242+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.849291+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.849308+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.849325+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.849341+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.854226+00:00Error: Not found: /_app/immutable/nodes/5.30954fa3.js
> 2023-09-11 13:33:00.854280+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.854297+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.854320+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.854364+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.854380+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.858097+00:00Error: Not found: /_app/immutable/chunks/_commonjsHelpers.725317a4.js
> 2023-09-11 13:33:00.858171+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.858219+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.858236+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.858252+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.858267+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.861655+00:00Error: Not found: /_app/immutable/chunks/index.86097c6b.js
> 2023-09-11 13:33:00.861725+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.861745+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.861761+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.861802+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.861818+00:00at async Array.ssr (file:///app/handler.js:1221:3)
> 2023-09-11 13:33:00.865371+00:00Error: Not found: /_app/immutable/chunks/utils.4ffa14d3.js
> 2023-09-11 13:33:00.865407+00:00at resolve (file:///app/server/index.js:3993:18)
> 2023-09-11 13:33:00.865442+00:00at resolve (file:///app/server/index.js:3827:34)
> 2023-09-11 13:33:00.865462+00:00at Object.handle (file:///app/server/chunks/hooks.server-d2584eb1.js:43:14)
> 2023-09-11 13:33:00.865490+00:00at async respond (file:///app/server/index.js:3825:22)
> 2023-09-11 13:33:00.865507+00:00at async Array.ssr (file:///app/handler.js:1221:3)

My ingress is working flawlessly with a lot of other stuff, therefore I don't know what could be wrong here...


Maybe this error is related to the attached storage?
Which mount paths do I have to attach to the container?
If I mount only `/data`, I get the following error:

> 2023-09-11 13:40:26.778963+00:00ln: /app/client/logos: Read-only file system

So in the end I added the mount path `/app/client` and since then the dashboard is at least starting up.

But well, without any stylesheets ^___^

**Comment by knrdl** [comment]
Ah ok, so the problem is that the container is running in readonly mode. Therefore it cannot start up because hubleys expect write access. Your /app/client volume mount introduces write access for this folder but overwrites the files in it. That's why you get the 404s. So please try to remove the readonly flag for this container.
