### ISSUE TITLE
NGINX + OAuth2/OIDC Guide

### ISSUE THREAD

**Issue by K-J-VV** [knrdl/hubleys-dashboard#220]
Very interested in this project, wondering if you may have a guide in the works for NGINX + OAuth2?

Would love to integrate this with an auth provider that is 'higher-function' than Authelia (i.e., authentik, Keycloak, etc.)

**Comment by knrdl** [comment]
hi there, currently I don't plan to integrate OAuth2 into hubleys. The design philosophy is that the auth provider really handles all auth stuff. Hubleys only consumes the trusted headers set by the auth provider (see [here](https://github.com/knrdl/hubleys-dashboard#3-configure-reverse-proxy--auth-provider)). That way it should integrate with **any** auth provider (with more or less config). Authelia is really just an example here.

Please have a look at [this PR](https://github.com/knrdl/hubleys-dashboard/pull/213/files) for an Authentik config. (The next hubleys release will also allow customizable header names, so it will become easier to configure.)

**Comment by K-J-VV** [comment]
I was actually able to get this going! Originally was getting the '500 foward auth provider not setup'. Then after connecting things via NGINX I was getting the authorization error. Finally figured out I needed to add the following line to the "/" location:

```
$upstream_http_x_auth_request_preferred_username;
proxy_set_header REMOTE-USER $user;

```

'The only follow up to this is any idea on what parameters to add to have the username, group, & email "cross" over? In Hubley, looks like the above parameter passes the username as the UserID? The rest of the user parameters are "null"

**Comment by knrdl** [comment]
`preferred_username` sounds like the OIDC claim, [the spec](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) lists the other claims you might need as well.

**Comment by K-J-VV** [comment]
Thanks for sharing that! Below is the best config I was able to setup for NGINX/OAuth claims to match. I have groups commented out because can't seem to figure that out. 

That being said.. do you think it can be made possible to manually set the groups of users? Considering my proxy/auth provider setup is not able to match group claims it would be **great** if there could be a way to still set/assign groups for users after they've connected to Hubley


`auth_request_set $user $upstream_http_x_auth_request_email;
auth_request_set $name $upstream_http_x_auth_request_preferred_username;
auth_request_set $email  $upstream_http_x_auth_request_preferred_username;
#auth_request_set $groups $upstream_http_x_auth_request_groups;
proxy_set_header REMOTE-USER $user;
proxy_set_header REMOTE-NAME $name;
proxy_set_header REMOTE-EMAIL $email;
#proxy_set_header REMOTE-GROUPS $groups;`

**Comment by K-J-VV** [comment]
Using the following meets my needs, will close ticket

`allow: [ user: xxx ]`
