### ISSUE TITLE
'search_engine' is incompatible with non "?q=" search queries

### ISSUE THREAD

**Issue by K-J-VV** [knrdl/hubleys-dashboard#221]
Testing out Hubley with a few search engines and it seems that any entry in the 'search_url' parameter is automatically appended with a "?q=" at the end. This makes it incompatible with search engines that have alternative search urls, like:

- example.com/?term=
- example.com/content/search?search=

Because when these search_url's are entered as is, what Hubley forwards users to is:

- example.com/?term=?q=
- example.com/content/search?search=?q=

If it helps for research, here is another project I've used that has a similar search bar function: https://github.com/jump-dev/JuMP.jl

I would think simply removing the appending of "?q=" to text within 'search_url' would fix the problem? Users would simply have to write the full search_url explicitely

Example:

- https://google.com/search   (currently acceptable)
vs
- https://google.com/search?q=     (following fix)

**Comment by knrdl** [comment]
hi, i've added a config option to solve this: see https://github.com/knrdl/hubleys-dashboard/blob/main/src/lib/server/sysconfig/default.yml#L11

**Comment by K-J-VV** [comment]
Perfect! Appreciate the work, looking forward to testing once the release image is updated

**Comment by knrdl** [comment]
new release

**Comment by K-J-VV** [comment]
Hello, me again lol Update is working great, but found that encoded URLs have an issue

Example query URL: ?action=Search&s=

When searched through Hubleys the URL is translated to: ?action%3DSearch%26s=

Resulting in incorrect end result

**Comment by knrdl** [comment]
updated the edge-tag, please try again

**Comment by K-J-VV** [comment]
> updated the edge-tag, please try again

Hmm, updated to edge and testing but looks like the end result URL is still translated 

Example query URL: ?action=Search&s=

When searched through Hubleys the URL is translated to a new tab as: ?action%3DSearch%26s=

**Comment by knrdl** [comment]
does your config look like *Test1* or *Test2*?
```yaml
  - title: Test1
    search_url: 'https://example.org?action=Search'
    search_parameter: s
    allow: true
  - title: Test2
    search_url: '?action=Search'
    search_parameter: s
    allow: true
```
In case of *Test2* you are missing the domain in the url. *Test2* executes the query against where Hubleys is running ... which is not supported for now

**Comment by K-J-VV** [comment]
@knrdl it _was_ like Test2; I tried Test1 and now its working great     Thank you!
