### ISSUE TITLE
Feature Request: use allow: true by default

### ISSUE THREAD

**Issue by dbondarchuk** [knrdl/hubleys-dashboard#224]
The title says it all :)

It is more user-friendly to use `allow: true` as the default option for tiles.

**Comment by knrdl** [comment]
in my opinion this is a safety question, because you don't want to show tiles to users by accident (in case of forgetting to add the allow rule). 
`allow: true` is a bit verbose for sure, but at least explicit.

**Comment by dbondarchuk** [comment]
I would argue that not much security as it is geared toward home users :)

**Comment by dbondarchuk** [comment]
As #233 was merged it addresses my concern here :)

**Comment by dbondarchuk** [comment]
With currently having sections with `allow` property, why it's necessary to have the allow on tiles?

**Comment by knrdl** [comment]
I agree, the current behavior is not consistent

**Comment by knrdl** [comment]
fixed by https://github.com/knrdl/hubleys-dashboard/commit/362651a22560b1541946b35f70ea7cd11b9d108c
