### ISSUE TITLE
Feature Request: Environment Variables to set default 'Settings' for all users

### ISSUE THREAD

**Issue by K-J-VV** [knrdl/hubleys-dashboard#225]
Would be nice to be able to set default settings for all users, i.e.,

- Background: Random Image
- Background_From: Unsplash photo library
- Query: cities
- Change_After: 10m
- Blur: true
etc.

**Comment by knrdl** [comment]
please have a look at the readme: `/data/users/default-config.json`

**Comment by K-J-VV** [comment]
Ahh, missed that. Awesome, thank you!!

**Comment by K-J-VV** [comment]
Hmm, I followed as directed in the readme but does not appear to be working.

Steps:
Copy Data From: /data/users/config/user1.json
Paste Text To: /data/users/default-config.json
Restart

Expected:
New users default to have identical config as user1.json

Result:
New users have standard default config


Also...
I placed an image in /data/favicon.png, but this does not appear to update correctly either

**Comment by knrdl** [comment]
please try to pull the edge tag again. your local version of the edge tag might be out of date. both (default config + favicon) are working for me

**Comment by K-J-VV** [comment]
default config is now working for me, but favicon is not. Trying to fiddle around to get something to work (changing image, etc.)       Will report back if find a resolution

**Comment by Rukongai** [comment]
I know it's a simple solution, but make sure for the favicon it's not cached. Try private window. I can confirm favicon is working for me as well

**Comment by K-J-VV** [comment]
Private browser did not work, but eventually updated!
