### ISSUE TITLE
User Config Settings

### ISSUE THREAD

**Issue by K-J-VV** [knrdl/hubleys-dashboard#226]
Few questions regarding default-config.json

- weather mode: when setting default to "lonlat", I'd imagine when a new user first joins the page Hubley's would request permission to their location, however this does not seem to be the case? Rather, user's still have to manually select zipcode or geolocation within settings. 

- While on the topic of weather... any chance can their be an added environment variable/config that would allow us to set default to imperial vs metric system for temp/windspeed/visability?

- show_settings_text:  when set to false does not appear to change anything. My understanding is this would disable the settings button so that users cannot modify backgrounds/weather/etc.

**Comment by knrdl** [comment]
> weather mode: when setting default to "lonlat", I'd imagine when a new user first joins the page Hubley's would request permission to their location, however this does not seem to be the case? Rather, user's still have to manually select zipcode or geolocation within settings.

that kind of function is not implemented, will look into it

> While on the topic of weather... any chance can their be an added environment variable/config that would allow us to set default to imperial vs metric system for temp/windspeed/visability?

I assume you americans will never be able to get along with the metric system ;)

Maybe this should be implemented as a per user setting and not an instance-wide config. I will look into it

> show_settings_text: when set to false does not appear to change anything. My understanding is this would disable the settings button so that users cannot modify backgrounds/weather/etc.

per default the settings link on the dashboard is icon+text. with the toggle set it will show just the icon

**Comment by knrdl** [comment]
imperial system can now be selected in settings, please test the edge tag

**Comment by K-J-VV** [comment]
> imperial system can now be selected in settings, please test the edge tag

Imperial toggle working great! [Just like how George Washington wanted](https://www.youtube.com/watch?v=JYqfVE-fykk&pp=ygUfZ2VvcmdlIHdhc2hpbmd0b24gbWV0cmljIHN5c3RlbQ%3D%3D)
