### ISSUE TITLE
Calendar Event Displays Incorrect Time

### ISSUE THREAD

**Issue by K-J-VV** [knrdl/hubleys-dashboard#242]
I've connected 2x ical calendars (one Google, one Outlook) and looks when you enter the detailed view for the calendar all events display as being from 6p-6p

![image](https://github.com/knrdl/hubleys-dashboard/assets/113187314/a01c34c3-6d3f-471f-8fc1-10d5a224a180)

But the times do appear correct on the default page
![image](https://github.com/knrdl/hubleys-dashboard/assets/113187314/9b2c38a9-9576-445a-87f1-4ebbd1368573)

**Comment by knrdl** [comment]
please try again with the `edge` tag

**Comment by K-J-VV** [comment]
All good!
