### ISSUE TITLE
Feature Request: Search Engine "Scrolling" and Search Bar Placement

### ISSUE THREAD

**Issue by K-J-VV** [knrdl/hubleys-dashboard#252]
**Search Engine "Scrolling"**
Currently if you want to select a new engine for the search bar you need to manually click the drop down box and then select the engine you want. Any idea if it'd be possible to turn this into a "scrollable" menu? i.e., Hover mouse over the box, use wheel to scroll up or down to select engine. 

This would be a very nice comfort feature 

**Search Bar Placement**
Could there be a toggle feature where the search bar is placed more in the center of the screen & made a bit larger so it is more prominent? Aesthetic similar to google is what I'm imagining

**Comment by knrdl** [comment]
> Search Engine "Scrolling"

Now possible in `edge` tag, please have a try

> Search Bar Placement

The current layout is:
1. Searchbar (on top)
2. Calendar (on top)
3. Messages (on top)
4. Tiles (on top/bottom, depending on settings)

How should the alternative layout look like?

**Comment by K-J-VV** [comment]
>> The current layout is:
> 
> 1. Searchbar (on top)
> 2. Calendar (on top)
> 3. Messages (on top)
> 4. Tiles (on top/bottom, depending on settings)
> 
> How should the alternative layout look like?

The biggest suggestion/preference I'd have for the layout is to first shift _everything_ down so there is some 'blank space' at the start of the webpage. One of my favorite aspects of a dashboard is having the customized splash image. In Hubleys the dashboard becomes quite cluttered and the background is hidden once there are several sections added to the config. If everything were shifted down the user can see most of the splash image at first load, then just scroll down to access tiles/sections of the dashboard. I attached a screenshot to show what I mean about the clutter. 

Generally speaking, I think having the Searchbar show in the bottom ~1/3 or ~1/4 of the webpage may look nice.


Then as a minor suggestion, the order of viewing which makes most sense to me is:
Messages
Searchbar
Calendar
Tiles

I consider Messages as temporary alerts that may change or not always be enabled. So having them appear higher seems appropriate. 


**Searchbar**
IMO, the search bar would be more aesthetic if it were larger, maybe more rounded. Personally, I'm a fan of the look of https://startpage.com 


![Untitled](https://github.com/knrdl/hubleys-dashboard/assets/113187314/7a4de7a9-fbd1-4b5f-b125-4f9e1b88ab07)

**Comment by K-J-VV** [comment]
Another possible layout could be something similar to the New Tab pages in Edge

In the image, the red box would be the Calendar. Then below the horizontal line is where you'd first see a Message and then after this Sections/Tiles would begin




![Untitled](https://github.com/knrdl/hubleys-dashboard/assets/113187314/cfa2fa57-b35f-40c7-961a-80ebf291746a)

**Comment by knrdl** [comment]
not sure if I understood your idea correctly. But I've added a "split layout" (on `edge` tag)
you can enable it via `Settings` → `Dashboard` → `settings.dashboard.position-split`

**Comment by K-J-VV** [comment]
You understood, it looks great! Definitely my personal preference for a layout

I'm not sure if this may be due to my monitor's size specifically, but if you see in the screenshot below it looks like the scroll bar doesn't default to the right-most side? Rather, it is floating off to the side and there is a gap

![image](https://github.com/knrdl/hubleys-dashboard/assets/113187314/14d2db46-4dae-4efe-8113-46b77cf56fce)

**Comment by K-J-VV** [comment]
And to follow up about **Search Engine "Scrolling"**

I'm not sure if this something entirely browser specific or if it can be controlled by Hubley's... Scrolling to change the search engine does work, but it also scrolls the entire webpage itself. It can be a slight issue if there are numerous search engines being used. 

In my example I have several search engines (e.g., Google, DuckDuckGo, Bing, etc.). I can Scroll from Google to DuckDuckGo, but by the time I scroll to the 3rd/4th/+ engine the webpage itself scrolls down and I cannot scroll further down the engine list without scrolling the entire page up and placing my mouse back over the Engine Selector.

Is it possible to set some key combination (e.g., Left CTRL + Mousewheel/Touchpad) that would specifically only scroll through the search engine list?


I hope that makes sense, please let me know if it isn't quite clear.

**Comment by knrdl** [comment]
> And to follow up about **Search Engine "Scrolling"**

should be fixed now. Changing search engine should not trigger a page scroll anymore

**Comment by knrdl** [comment]
> I'm not sure if this may be due to my monitor's size specifically, but if you see in the screenshot below it looks like the scroll bar doesn't default to the right-most side? Rather, it is floating off to the side and there is a gap

I cannot reproduce this with firefox nor opera (chrome engine). Which browser do you use?
I made the scrollbar thinner anyways.

**Comment by K-J-VV** [comment]
@knrdl thank you!! It's looking good
