### ISSUE TITLE
Calculator Button

### ISSUE THREAD

**Issue by K-J-VV** [knrdl/hubleys-dashboard#253]
Could there be an integrated calculator? Either as a separate button or another tab option next to the Stopwatch & Timer?

A button below the calendar may be good placement too (toggle option for those not wanting it)

**Comment by knrdl** [comment]
Good idea. But I don't think this needs an extra implementation. You can either add a tile to link to a calculator. Or add one as search engine: I've added wolfram alpha as an example in https://github.com/knrdl/hubleys-dashboard/commit/f48ddab9db605306ba05eff2be10bc446b49e8ce
