### ISSUE TITLE
Feature Request: set admins following groups

### ISSUE THREAD

**Issue by marouamghar** [knrdl/hubleys-dashboard#257]
Hey, it seems the only way to setup a user as an admin is to add its userId to the compose file. Would it be possible to also handle a groupId, so that all users belonging to that said group would be set as admins?

**Comment by knrdl** [comment]
I've replaced the env var `ADMIN_USERIDS` with a more general `ADMINS`: 
```diff
- ADMIN_USERIDS: user1, user2
+ ADMINS: user:user1, user:user2, group:admins
```

please try with the `edge` tag image: `ghcr.io/knrdl/hubleys-dashboard:edge`

**Comment by marouamghar** [comment]
working great, thanks man !
