### ISSUE TITLE
Tab Name Customization 

### ISSUE THREAD

**Issue by K-J-VV** [knrdl/hubleys-dashboard#258]
Would it be possible to change how the 'Dashboard' page's name is displayed in tabs?

I'd like to set my instance to 'Home', but other users may want to customize to 'Hubley's', or 'Dash', or etc.

![image](https://github.com/knrdl/hubleys-dashboard/assets/113187314/ee6daf15-02b5-4bf0-803f-04efdde60dd4)

**Comment by knrdl** [comment]
i've just set it to "Home". I think that is good enough, until someone needs a more elaborated solution.

**Comment by K-J-VV** [comment]
The only real benefit would be just personal customization/preference. Personally, just very interested in having the ability to tweak and customize

A possible easy way to implement would be setting some environment variable, but for now I'm just happy with Home!
