### ISSUE TITLE
How to open link in same tab?

### ISSUE THREAD

**Issue by Ra72xx** [knrdl/hubleys-dashboard#260]
Maybe I'm just missing a configuration option, but how do I open a link not in a new tab, but in the same (i.e. hubley's) tab?

**Comment by knrdl** [comment]
No, that is not possible, yet. Do you want to let each user decide if same tab / new tab (user settings). Or do you want to control this behavior for each link instead (tiles config)?

**Comment by Ra72xx** [comment]
I would prefer something like an additional "target=..." tag for each link. 
Background: I try to use hubleys as a dashboard embedded in my Nextcloud instance. Many other homelab sites could also be opened embedded, others have to opened in a new tab (e.g. internal only sites). This should be configurable on a per-link basis.

**Comment by knrdl** [comment]
I've added the feature. Please try with the edge tag docker image:  `ghcr.io/knrdl/hubleys-dashboard:edge`

change in config.yml:
```diff
- url: https://github.com/cmatsuoka/asciiquarium
+ url:
+  value: https://github.com/cmatsuoka/asciiquarium
+  # tab: 'new'  # the default, will open the link in a new tab
+  tab: 'same' # will open the link in the current tab
```

**Comment by Ra72xx** [comment]
Thanks for the quick fix.

**Comment by Ra72xx** [comment]
Could you also implement "top" and/or "parent" for this configuration option?

**Comment by knrdl** [comment]
now possible (when the `edge` build is done) via this format change in your config.yml file:
[src/lib/server/sysconfig/types.d.ts](https://github.com/knrdl/hubleys-dashboard/commit/1322d5a19add3840fe420bf0329e34b76bfefdb6#diff-518594634629650f8ed3ccee1dd2dbd3b76d69d1f48d3697ed6c3336838d7f54L4-R4)

**Comment by Ra72xx** [comment]
That are about the fastest feature request implementations I've experienced until now ;-).

**Comment by Ra72xx** [comment]
Unfortunately, it does not work yet (using ghcr.io image with edge-tag):
```
      - title: Nextcloud
        logo: https://nextcloud.domain:8443/icons/general/nextcloud.png
        url: https://nextcloud.domain:8443/nextcloud/
        target: same-tab
        subtitle: Nextcloud
```
This should open in the same tab, as I understand it, but it always opens a new tab?

**Comment by knrdl** [comment]
no, it should be:
```yaml
      - title: Nextcloud
        logo: https://nextcloud.domain:8443/icons/general/nextcloud.png
        url: 
          value: https://nextcloud.domain:8443/nextcloud/
          target: same-tab
        subtitle: Nextcloud
```
