### ISSUE TITLE
GUI Method for Users to Add Sections + Tiles

### ISSUE THREAD

**Issue by K-J-VV** [knrdl/hubleys-dashboard#263]
Just curious to know if there are any plans down the road for some sort of GUI interface that allows modification of the dashboard?

If it is ever implemented, it would be nice if there can be layers of authority. E.g., Public/Admin created sections/tiles are fixed and cannot be modified or edited by users. Any User created section/tiles are added to the bottom of the config file so they appear below the higher authority Admin sections/tiles

**Comment by knrdl** [comment]
No, this is not currently planned. Hubleys was really just meant as a way to hand out links to users and therefore grew into this dashboard thing.

**Comment by K-J-VV** [comment]
Gotchya, thanks for response! I'm a huge fan of self-hosted dashboards and honestly Hubleys is just great. The only one that comes _close_ is Homarr, and its standout feature to me is the ease of customizing the dashboard via GUI
