### ISSUE TITLE
Larger Layout Size For Menu Tiles

### ISSUE THREAD

**Issue by K-J-VV** [knrdl/hubleys-dashboard#470]
As my Hubley dashboard grows I am starting to accumulate more & more links to certain apps. Once I reach ~10+ Tiles in a Menu I can no longer see/click the Tiles that are at the end of the list.

It looks like the default Menu layout is an infinite length of 2 columns. 

Would it be possible to make the menu size customizable? Either allow users to specify the number of columns, include some sort of scroll bar, or see if there is a way the Menu can autofill the screen size once opened? (similar to how the dashboard layout works)  

Example Of Having 'Too Many' Tiles within A Single Menu: 

![Screenshot 2024-12-16 081521](https://github.com/user-attachments/assets/000ac397-d2ba-48d1-a904-9c0f8e3a72c8)

**Comment by knrdl** [comment]
I've never thought about menus becoming so large ^^
Please have a try with `docker pull ghcr.io/knrdl/hubleys-dashboard:edge` (edge tag)

**Comment by K-J-VV** [comment]
@knrdl awesome, update is great! 

Circling back to rebuilding my homelab and its gotten quite large lol

[still trying to figure out the issue I'm having with getting my OAuth setup to work well with Hubleys](https://github.com/knrdl/hubleys-dashboard/issues/259#issuecomment-2094869658), no luck yet

**Comment by knrdl** [comment]
@K-J-VV I've published a new release

> https://github.com/knrdl/hubleys-dashboard/issues/259#issuecomment-2094869658, no luck yet

You can try this reflecting server https://github.com/traefik/whoami for debugging purposes
